### PR TITLE
Change Scrivener.SEO to Scrivener.HTML.SEO

### LINKED ISSUE #63: Compilation error in v1.7
Getting this error when building with v1.7:

```
Compiling 28 files (.ex)

== Compilation error on file web/views/page_view.ex ==
** (CompileError) web/views/page_view.ex:3: module Scrivener.SEO is not loaded and could not be found
```

It looks like the `using` introduced in #59 is referring to `Scrivener.SEO` but the module is actually named [`Scrivener.HTML.SEO`](https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html/seo.ex#L1)?

### PR DESCRIPTION
**Pull request by lee-dohm**
Fixes #63

* Tested locally on my own project
* Ran `mix test` to ensure no breakage

### CODE REVIEW

**Comment by mgwidmann** [comment]
Whats the purpose? Its better organization, I'm just concerned with people using it I'll have bump the major version...

**Comment by mgwidmann** [comment]
nvm, sorry didnt see the issue in #63
