### ISSUE TITLE
Compilation error in v1.7

### ISSUE THREAD

**Issue by lee-dohm** [mgwidmann/scrivener_html#63]
Getting this error when building with v1.7:

```
Compiling 28 files (.ex)

== Compilation error on file web/views/page_view.ex ==
** (CompileError) web/views/page_view.ex:3: module Scrivener.SEO is not loaded and could not be found
```

It looks like the `using` introduced in #59 is referring to `Scrivener.SEO` but the module is actually named [`Scrivener.HTML.SEO`](https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html/seo.ex#L1)?

**Comment by mgwidmann** [comment]
`v1.7.1` released on hex, thanks for the issue!

**Comment by lee-dohm** [comment]
Thank you for the great utility! :bow:
